### ISSUE TITLE
Can't parse article from nymag.com despite GDPR cookie in site-config

### ISSUE THREAD

**Issue by shtrom** [j0k3r/graby-site-config#34]
I am trying to import http://nymag.com/selectall/2018/04/an-apology-for-the-internet-from-the-people-who-built-it.html into Wallabag, but keep getting the GDPR consent page instead.

The site-config seems to have the right cookie:
```
http_header(Cookie): nymuc=1111111111111
```

I even replaced it with that cookie,, and both others, that my browser had, but I keep getting the page, regardless of whether I reload the entry, or delete it and re-add the URL.

I cleared the Wallabag PHP cache, to no avail.

PS: Not sure whether this should be a Wallabag or ftr-site-config issue, so I went for the middle ground; please let me know if another repo is better indicated.

**Comment by j0k3r** [comment]
Have you tried to change the referer and / or the user agent?

**Comment by shtrom** [comment]
I just tried it out, but it didn't fix the issue:

```
http_header(user-agent): Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0                                                                                           
```

**Comment by shtrom** [comment]
Heh...  It seems to be working now...
