### ISSUE TITLE
Issue with nextinpact config

### ISSUE THREAD

**Issue by Pofilo** [j0k3r/graby-site-config#38]
Hello,

I have an issue with "nextinpact.com.txt". The long articles are not completely grabbed.
The article in `test_url` is too small to see the problem. And I don't find any documentation on how to run the tests.

Thanks for your help.

**Comment by j0k3r** [comment]
I just tried with a long article while being logged in (I've a paid account) and every thing works great.
The page: https://www.nextinpact.com/news/108880-un-an-apres-grand-debat-grand-absent-financement-pour-recherche.htm

And the content from wallabag:
![image](https://user-images.githubusercontent.com/62333/78880411-a955c200-7a55-11ea-8f1f-3ae29ad29bee.png)

If you still have the error please share more information:
- the related url which failed to be parsed
- are you logged in or not?

**Comment by Pofilo** [comment]
It is working again on my instance too. So I have no idea what the problem was.
Thanks for your time, and sorry for this _false_ problem.
